### ISSUE TITLE
timezone correction not used

### ISSUE THREAD

**Issue by 532910** [mvmike/min-cal-widget#29]
when i have a record in a calendar before 3am the dot is shown a day before
i'm in msk which is gmt+3

**Comment by mvmike** [comment]
Should be corrected in #28, could you please try with the latest release?

Will need to add some tests for those cases in the app, though... there isn't any now :sweat_smile:

**Comment by c-e-p-x-u-o** [comment]
Not fixed in v1.0.0.

**Comment by mvmike** [comment]
Not able to reproduce it :disappointed:. Could you please provide the following information?

- Device clock timezone
- Event's calendar timezone
- Exact start and end time for the event

**Comment by c-e-p-x-u-o** [comment]
> * Device clock timezone
System -> Date & time -> Select time zone: GMT +03:00 Moscow Standard Time

> * Event's calendar timezone
Moscow Standard Time GMT+3

> * Exact start and end time for the event
2018-11-15 01:00 --- 2018-11-15 02:00

**Comment by mvmike** [comment]
Could you please reopen it? It seems that "all day" event instances are in UTC but those that are not are in system time zone :upside_down_face:

**Comment by c-e-p-x-u-o** [comment]
only you can reopen it

**Comment by mvmike** [comment]
right :sweat_smile:

**Comment by mvmike** [comment]
corrected in v.1.0.1

**Comment by c-e-p-x-u-o** [comment]
Thank you!

**Comment by aereaux** [comment]
It looks like I'm still getting an issue similar to this (although I'm in a negative timezone and so the event appears on the day after).  Should I open another issue?

**Comment by mvmike** [comment]
Hi @aereaux,

Could you please provide more information to try to reproduce the issue? I think it should be enough with the data about the event that leaks to the wrong day and system timezone.

**Comment by aereaux** [comment]
My timezone is currently PST (UTC -8).  To reproduce I created an event with timezone GMT (UTC -0) and a time of 03:00 Sunday Jan 21 2024.  This event appears in Etar in the proper time on the 20th in my timezone but on the 21st in min-cal.  If it helps I can try and share an ICS file or provide any other system settings needed for debugging.

Thanks!

**Comment by mvmike** [comment]
Hi @aereaux,

Did a bit of testing, both in code and in the emulator and could not reproduce the issue

| Widget | Instance | System time zone |
| --------- | ------------ | ------------ |
| ![Screenshot_20240102_112037](https://github.com/mvmike/min-cal-widget/assets/20406251/d5cfc8e1-9ffa-40d2-921b-91c0e750157b) | ![Screenshot_20240102_112104](https://github.com/mvmike/min-cal-widget/assets/20406251/209ae25f-eb7d-4788-95d4-dffd09d22eb5) | ![Screenshot_20240102_112129](https://github.com/mvmike/min-cal-widget/assets/20406251/dded7a05-4d10-43f3-afc9-1afb87734f62) |

May I suggest that you clear the storage and cache of the "Calendar Storage" system app? It happened to me once or twice that it was showing outdated data through the Calendar API. If the issue still persists, I'd be very helpful to get an ICS with the exact event details 🙏🏻

**Comment by aereaux** [comment]
I think you're seeing the same thing that I'm seeing, the event appears on the 21st when it's on the 20th in my local timezone.  Is that expected behavior?

**Comment by mvmike** [comment]
Now I see what you mean... Currently, events are shown in a specific day if that event is inside the day in its own timezone, but looking at how all calendars behave, it should definitely work as you mentioned and consider the system time zone (the issue is hard to spot if your calendar/instances are in the same timezone as your device, which is my case).

Appreciate a lot the report, @aereaux!

**Comment by aereaux** [comment]
Thanks!  Yeah, I only noticed it because of an ICS file that gets imported in my timezone on the phone vs in UTC when synced from caldav.

**Comment by mvmike** [comment]
Fixed in 3ce92398edb634ef176cbdcea68fffb8c524c38e, which is included in [v2.16.0](https://github.com/mvmike/min-cal-widget/releases/tag/v2.16.0)
